dubbo:
  application:
    name: user-service
  registry:
    address: zookeeper://zookeeper.metropolis.com:2181?backup=zookeeper1.metropolis.com:2182,zookeeper2.metropolis.com:2181
    simplified: true
    group: dubbo-user-service
  scan:
    base-packages: com.metropolis.service
  metadata-report:
    address: zookeeper://zookeeper.metropolis.com:2181?backup=zookeeper1.metropolis.com:2182,zookeeper2.metropolis.com:2181
    group: dubbo-user-service
    retry-times: 30
